### ISSUE TITLE
Datalist children

### ISSUE THREAD

**Issue by oliverjam** [FAC-Sixteen/week4-daabest#16]
I know this is probably unfinished code, but just thought I'd point out that `<datalist>` elements take `<option>`s as children directly. You don't need a `<select>` in there.

https://github.com/FAC-Sixteen/week4-daabest/blob/c166f31c2771581c1aa31417d0f644a0210ad2a7/public/index.html#L20

Also the `<input>` that controls the datalist should have a `list="id-of-datalist"` attribute. More info [on the MDN datalist article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist)

**Comment by aniablaziak** [comment]
Thanks! That's very helpful, it was one of the last things we were working on last night and couldn't figure out why the appended elements were not displaying.

**Comment by oliverjam** [comment]
Glad I could help!

Just an FYI—generally it's a good idea to keep issues open until you push code that actually fixes them, to keep track :) You can relate a commit or PR to an issues by adding e.g. "relates #12" to make it show up here
