### ISSUE TITLE
no .gitignore

### ISSUE THREAD

**Issue by ZooeyMiller** [FAC-Sixteen/week4-daabest#17]
You haven't got a `.gitignore` meaning you've committed various things that shouldn't be committed, such as `node_modules` and `.DS_store`, please make sure to use a `.gitignore` in future. Github can generate this for you when you make the repo :sparkles:

**Comment by RohanSSS** [comment]
it seems like they do actually have a .gitignore, but it's not actually working for some reason

**Comment by oliverjam** [comment]
Yeah I think because `node_modules` is a directory the `.gitignore` entry needs to be `node_modules/` (with the slash)

**Comment by ZooeyMiller** [comment]
Ah, good point, I think it's probably because the `node_modules` etc were committed before the info in the git ignore was added. a gitignore won't retrospectively ignore stuff that has already been committed. Something along these lines will be needed: https://gist.github.com/lmcneel/45594e550a3403d589bdcaad38138a83

**Comment by tloth** [comment]
Yes, we accidentally pushed node_modules, and added .gitignore later.
Followed the instructions in the link, thank you all!
![goodie](https://66.media.tumblr.com/tumblr_lnxnbzwxDQ1qdjj7e.gif)
